[manifest]
version = "1.0.0"
dump_lua = true
priority = 11

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "RENTAL = HEX('b18f43'),"
position = "after"
match_indent = true
payload = '''
DRAGQUEEN_LIGHT_SUIT = HEX('F06841'),
DRAGQUEEN_DARK_SUIT = HEX('3C4A4E'),
DRAGQUEEN_PUMPS_LC = HEX('ecb6db'),
DRAGQUEEN_PUMPS_HC = HEX('ecb6db'),
DRAGQUEEN_PURSES_LC = HEX('eec39a'),
DRAGQUEEN_PURSES_LC = HEX('eec39a'),
'''


[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.LOC_COLOURS = G.ARGS.LOC_COLOURS or {"
position = "after"
match_indent = true
payload = '''
  dragqueen_pumps = G.C.SUITS.dragqueen_Pumps or G.C.DRAGQUEEN_PUMPS_LC,
  dragqueen_purses = G.C.SUITS.dragqueen_Purses or G.C.DRAGQUEEN_PURSES_LC,
  rgmc_blooms = G.C.SUITS.rgmc_blooms or G.C.RGMC_BLOOMS or HEX('A7EE5F'),
  rgmc_daggers = G.C.SUITS.rgmc_daggers or G.C.MC_DAGGERS or HEX('591235'),
  rgmc_lanterns = G.C.SUITS.rgmc_lanterns or G.C.MC_LANTERNS or HEX('F09B4A'),
  rgmc_voids = G.C.SUITS.rgmc_voids or G.C.MC_VOIDS or HEX('564C53'),
'''