[manifest]
version = "1.0.0"
dump_lua = true
priority = 11

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "RENTAL = HEX('b18f43'),"
position = "after"
match_indent = true
payload = '''
DRAGQUEEN_LIGHT_SUIT = HEX('D4D4D4'),
DRAGQUEEN_DARK_SUIT = HEX('323232'),
DRAGQUEEN_DARK_AND_LIGHT_SUIT = {0.513, 0.513, 0.513, 1},
DRAGQUEEN_PUMPS_LC = HEX('ecb6db'),
DRAGQUEEN_PUMPS_HC = HEX('ecb6db'),
DRAGQUEEN_PURSES_LC = HEX('eec39a'),
DRAGQUEEN_PURSES_LC = HEX('eec39a'),
DRAGQUEEN_KEYWORD = {0,0,1,1},
DRAGQUEEN_RAINBOW = {0,0,1,1},
BUNC_EXOTIC_SUIT = {0,0,1,1},
DRAGQUEEN_PLAIN_SUIT = {0,0,1,1},
DRAGQUEEN_ACCESSORY_SUIT = {0,0,1,1},
DRAGQUEEN_BUNC_EXOTIC_SUIT = {0,0,1,1},
DRAGQUEEN_PAPERBACK_PROUD_SUIT = {0,0,1,1},
DRAGQUEEN_SIX_NIGHT_SUIT = {0,0,1,1},
DRAGQUEEN_MINTY_TREAT_SUIT = {0,0,1,1},
DRAGQUEEN_MTG_MAGIC_SUIT = {0,0,1,1},
DRAGQUEEN_INK_STAINED_SUIT = {0,0,1,1},
DRAGQUEEN_RGMC_PARALLEL_SUIT = {0,0,1,1},
DRAGQUEEN_RGMC_CHAOTIC_SUIT = {0,0,1,1},
DRAGQUEEN_UNIK_TICTACTOE_SUIT = {0,0,1,1},
'''


# [[patches]]
# [patches.pattern]
# target = "functions/misc_functions.lua"
# pattern = "G.ARGS.LOC_COLOURS = G.ARGS.LOC_COLOURS or {"
# position = "after"
# match_indent = true
# payload = '''
# dragqueen_pumps = G.C.SUITS.dragqueen_Pumps or G.C.DRAGQUEEN_PUMPS_LC,
# dragqueen_purses = G.C.SUITS.dragqueen_Purses or G.C.DRAGQUEEN_PURSES_LC,
# dragqueen_keyword = G.C.DRAGQUEEN_KEYWORD,
# dragqueen_rainbow = G.C.DRAGQUEEN_RAINBOW,
# rgmc_blooms = G.C.SUITS.rgmc_blooms or G.C.RGMC_BLOOMS or HEX('A7EE5F'),
# rgmc_daggers = G.C.SUITS.rgmc_daggers or G.C.RGMC_DAGGERS or HEX('591235'),
# rgmc_lanterns = G.C.SUITS.rgmc_lanterns or G.C.RGMC_LANTERNS or HEX('F09B4A'),
# rgmc_voids = G.C.SUITS.rgmc_voids or G.C.RGMC_VOIDS or HEX('564C53'),
# ink_inks = G.C.SUITS.ink_Inks or G.C.INK_INKS or HEX('374649'),
# ink_colors = G.C.SUITS.ink_Colors or G.C.INK_COLORS or HEX('eb8920'),
# '''


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.TIMERS.TOTAL = self.TIMERS.TOTAL + dt*(self.SPEEDFACTOR)"
position = "after"
match_indent = true
payload = '''
local wavy_colors = DRAGQUEENMOD.wavy_color_updater(self.TIMERS.REAL)
for color, value in pairs(wavy_colors) do
  self.C[color][1] = value[1]
  self.C[color][2] = value[2]
  self.C[color][3] = value[3]
  self.C[color][4] = value[4]
end
'''
